<?php

namespace Database\Seeders;

use App\Models\brands;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $brands = [
            ["brand_name"=>"Agrale"],
            ["brand_name"=>"Astra"],
            ["brand_name"=>"Avia"],
            ["brand_name"=>"Bremach"],
            ["brand_name"=>"Citroen"],
            ["brand_name"=>"Daewoo"],
            ["brand_name"=>"DAF"],
            ["brand_name"=>"Fiat"],
            ["brand_name"=>"Ford"],
            ["brand_name"=>"GMC"],
            ["brand_name"=>"Hino"],
            ["brand_name"=>"Isuzu"],
            ["brand_name"=>"Iveco"],
            ["brand_name"=>"Lexea"],
            ["brand_name"=>"Mahindra"],
            ["brand_name"=>"MAN"],
            ["brand_name"=>"Mercedes"],
            ["brand_name"=>"Mercedes-Benz"],
            ["brand_name"=>"Mitsubishi"],
            ["brand_name"=>"Mitsubishi Fuso"],
            ["brand_name"=>"Nissan"],
            ["brand_name"=>"Peterbilt"],
            ["brand_name"=>"Peugeot"],
            ["brand_name"=>"Renault"],
            ["brand_name"=>"Scania"],
            ["brand_name"=>"Tata"],
            ["brand_name"=>"Toyota"],
            ["brand_name"=>"Vauxhall"],
            ["brand_name"=>"Volkswagen"],
            ["brand_name"=>"Volvo"],
            ["brand_name"=>"Yuejin"],
            ["brand_name"=>"Abarth"],
            ["brand_name"=>"Alfa Romeo"],
            ["brand_name"=>"Alpine"],
            ["brand_name"=>"Aston Martin"],
            ["brand_name"=>"Audi"],
            ["brand_name"=>"Bentley"],
            ["brand_name"=>"BMW"],
            ["brand_name"=>"Brilliance"],
            ["brand_name"=>"Bugatti"],
            ["brand_name"=>"Buick"],
            ["brand_name"=>"Cadillac"],
            ["brand_name"=>"Caterham"],
            ["brand_name"=>"Chery"],
            ["brand_name"=>"Chevrolet"],
            ["brand_name"=>"Chrysler"],
            ["brand_name"=>"Corvette"],
            ["brand_name"=>"Cupra"],
            ["brand_name"=>"Dacia"],
            ["brand_name"=>"Daihatsu"],
            ["brand_name"=>"Daimler"],
            ["brand_name"=>"Datsun"],
            ["brand_name"=>"Dodge"],
            ["brand_name"=>"Donkervoort"],
            ["brand_name"=>"Dr Motor"],
            ["brand_name"=>"DS Automobiles"],
            ["brand_name"=>"Ferrari"],
            ["brand_name"=>"Force"],
            ["brand_name"=>"Great Wall"],
            ["brand_name"=>"Gwm"],
            ["brand_name"=>"Holden"],
            ["brand_name"=>"Honda"],
            ["brand_name"=>"Hyundai"],
            ["brand_name"=>"Infiniti"],
            ["brand_name"=>"Jaguar"],
            ["brand_name"=>"Jeep"],
            ["brand_name"=>"Kia"],
            ["brand_name"=>"KTM"],
            ["brand_name"=>"Lamborghini"],
            ["brand_name"=>"Lancia"],
            ["brand_name"=>"Land Rover"],
            ["brand_name"=>"Lexus"],
            ["brand_name"=>"Lincoln"],
            ["brand_name"=>"Lotus"],
            ["brand_name"=>"LTI Taxis"],
            ["brand_name"=>"Luxgen"],
            ["brand_name"=>"Maruti Suzuki"],
            ["brand_name"=>"Maserati"],
            ["brand_name"=>"Maybach"],
            ["brand_name"=>"Mazda"],
            ["brand_name"=>"McLaren"],
            ["brand_name"=>"Metrocab"],
            ["brand_name"=>"MG"],
            ["brand_name"=>"Mini"],
            ["brand_name"=>"Morgan"],
            ["brand_name"=>"Opel"],
            ["brand_name"=>"Oreion"],
            ["brand_name"=>"Oreion Motors"],
            ["brand_name"=>"Pontiac"],
            ["brand_name"=>"Porsche"],
            ["brand_name"=>"Premier"],
            ["brand_name"=>"Proton"],
            ["brand_name"=>"Rolls Royce"],
            ["brand_name"=>"Rover"],
            ["brand_name"=>"Saab"],
            ["brand_name"=>"Saturn"],
            ["brand_name"=>"Scion"],
            ["brand_name"=>"Seat"],
            ["brand_name"=>"Shelby"],
            ["brand_name"=>"Skoda"],
            ["brand_name"=>"Smart"],
            ["brand_name"=>"SsangYong"],
            ["brand_name"=>"Subaru"],
            ["brand_name"=>"Suzuki"],
            ["brand_name"=>"Troller"],
            ["brand_name"=>"Verte"],
            ["brand_name"=>"Volga"],
            ["brand_name"=>"LDV"],
            ["brand_name"=>"Maruti"],
            ["brand_name"=>"Piaggio"],
            ["brand_name"=>"Case"],
            ["brand_name"=>"Claas"],
            ["brand_name"=>"Deutz-Fahr"],
            ["brand_name"=>"Fendt"],
            ["brand_name"=>"John Deere"],
            ["brand_name"=>"Landini"],
            ["brand_name"=>"Linde AG"],
            ["brand_name"=>"Massey Ferguson"],
            ["brand_name"=>"McCormick"],
            ["brand_name"=>"New Holland"],
            ["brand_name"=>"Auto-Trail"],
            ["brand_name"=>"CI Motorhomes"],
            ["brand_name"=>"Hymer"],
            ["brand_name"=>"Rimor"],
            ["brand_name"=>"Rollerteam"],
            ["brand_name"=>"Tempo Libero"],
            ["brand_name"=>"Trigano"],
            ["brand_name"=>"Caterpillar"],
            ["brand_name"=>"Bburg"],
        ];

        foreach($brands as $brand){
            brands::create($brand);
        }

    }
}
